version: '3.0'
services:
  tensorflow:
    container_name: tensorflow-jupyter
    image: tensorflow/tensorflow:latest-gpu-jupyter
    restart: unless-stopped
    volumes:
      - ./notebooks:/tf/notebooks
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ports:
      - '8888:8888'
      - '6006:6006'
    networks:
      - jupyter
networks:
  jupyter:
    driver: bridge